server:
  tomcat:
    connection-timeout: 20s
  forward-headers-strategy: framework
  error:
    include-message: always
merlin:
  open-ai-api-key: key
spring:
  session:
    store-type: memory
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
  main:
    lazy-initialization: true
