spring:
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: ALWAYS
      cleanup-cron: 0 0 1 * * *
  datasource:
    hikari:
      max-lifetime: 240000 # 4 minutes
  autoconfigure:
    exclude: [ ]
