spring:
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: ALWAYS
  datasource:
    hikari:
      max-lifetime: 240000 # 4 minutes
  autoconfigure:
    exclude: [ ]
server:
  servlet:
    session:
      cookie:
        secure: true
