server:
  tomcat:
    connection-timeout: 20s
  forward-headers-strategy: framework
merlin:
  open-ai-api-key: key
spring:
  session:
    jdbc:
      initialize-schema: ALWAYS
      cleanup-cron: 0 0 1 * * *
  datasource:
    hikari:
      max-lifetime: 600000 # 10 minutes
